
# This base is copied to $AIIL_PANTHER_CHECKOUT_DIR/.basrhc by the build_setup script

# Aliases
alias grep='grep --color=auto'
alias vi="vim"
alias ..="cd .."

# Dir Stack
function pn_stack()
{
    lines=`dirs | wc -w | sed -E -e 's/ +//'`
    lines=`expr $lines - 1`
    echo
    echo "Dir Stack"
    dirs -v | tail -$lines | sort -rn | sed -e 's/^/    /'
}

function pn_pushd()
{
    pushd $1 > /dev/null;
    pn_stack
}

alias pd='pn_pushd'
alias pp='popd > /dev/null; pn_stack'


# ROS Parameter Settings
unset ROS_IPV6
#unset ROS_HOSTNAME
export ROS_HOSTNAME=`hostname`

# Function to set master
function set_ros_master() {
    export ROS_MASTER_URI=http://$1:11311
    echo "Setting: ROS_MASTER_URI=$ROS_MASTER_URI"
}

# Set ROS IP using default (or provided) argument
function set_ros_ip() {
    unset ROS_HOSTNAME
    if [[ $# -eq 0 ]] ; then
        export ROS_IP=`hostname -I | awk '{print $1}'`
    else
        export ROS_IP=$1
    fi
    echo "Unset: ROS_HOSTNAME"
    echo "Setting: ROS_IP=$ROS_IP"
}

# Set ROS HOSTNAME using default (or provided) argument
function set_ros_hostname() {
    unset ROS_IP
    if [[ $# -eq 0 ]] ; then
        export ROS_HOSTNAME=`hostname`
    else
        export ROS_HOSTNAME=$1
    fi
    echo "Unset: ROS_IP"
    echo "Setting: ROS_HOSTNAME=$ROS_HOSTNAME"
}

