# This is the default docker compose file that is use to configure `docker compose`
# Note this file IS NOT read on robot boot
# Instead services here should use `restart: always` to be loaded on boot
#
# To change the docker containers launched on boot
# 1. Modify this file
# 2. Stop all docker containers (`docker compose stop`)
# 3. Restart this file (`docker compose --project-name --project-name my-project -f compose.yaml up`)
#
# This uses the project name 'rmit_panther_compose'
#
# Then the files should launch on start-up


services:

  panther_tracking:
    image: panther_zed:test
    container_name: panther_take_zed_images
    network_mode: host
    ipc: host
    tty: true
    environment:
      - ROS_IP=10.15.20.3
      - ROS_MASTER_URI=http://10.15.20.2:11311
    command: roslaunch first_pkg take_zed_images.launch --wait
